version: '3.8'


services:
  hycx.ac.app: # 容器名
    build: .
    ports:
      - "${CONTAINER_PORT}:${GRADIO_APP_SERVER_PORT}"  # 将主机的PORT端口映射到容器的22端口
    volumes:
      - ./data:${DATA_PATH} # 替换容器内的挂载路径
    restart: always